spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: mmani
  jpa:
    show-sql: true